name: Deploy API

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-to-production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch secrets from Vault
        uses: hashicorp/vault-action@v3
        with:
          url: ${{ vars.VAULT_ADDR }}
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          exportEnv: true
          secrets: |
            kv/data/shared DOCKERHUB_USERNAME | DOCKERHUB_USERNAME;
            kv/data/shared DOCKERHUB_ACCESS_TOKEN | DOCKERHUB_TOKEN;
            kv/data/api DROPLET_IP | DROPLET_IP;
            kv/data/api SSH_PRIVATE_KEY | SSH_KEY;

      - name: Write SSH key to file
        run: |
          echo "$SSH_KEY" > $GITHUB_WORKSPACE/ssh_key
          chmod 600 $GITHUB_WORKSPACE/ssh_key

      - name: Build commit image
        run: sudo docker build -t ${{ env.DOCKERHUB_USERNAME }}/personal-website-api:${{ github.sha }} .

      - name: Tag commit image as latest
        run: sudo docker tag ${{ env.DOCKERHUB_USERNAME }}/personal-website-api:${{ github.sha }} ${{ env.DOCKERHUB_USERNAME }}/personal-website-api:latest

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Push Docker images to Docker Hub
        run: |
          docker push ${{ env.DOCKERHUB_USERNAME }}/personal-website-api:${{ github.sha }}
          docker push ${{ env.DOCKERHUB_USERNAME }}/personal-website-api:latest

      - name: Copy docker-compose file to droplet
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ env.DROPLET_IP }}
          username: deploy
          key_path: ${{ github.workspace }}/ssh_key
          source: docker-compose.yml
          target: "~/personal-website-api"

      - name: Deploy to DigitalOcean droplet
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ env.DROPLET_IP }}
          username: deploy
          key_path: ${{ github.workspace }}/ssh_key
          script: |
            cd ~/personal-website-api
            docker pull ${{ env.DOCKERHUB_USERNAME }}/personal-website-api:latest
            docker compose up -d --remove-orphans personal-website-api
